export const data = {
'pongHTML':"<img height=250px width=400px src=./src/media/pongGame.png><h3>Networked 6 Player Pong</h3><p>This is a networked 6-player pong game. Built in node.js, this web app uses near real-time communication combined with lerping algorithms to give each user a similar experience.</p><a href=https://crazy-6-pong.herokuapp.com/>Live Demo</a><a href=https://github.com/LegendaryBaddie/project2>Github</a>",
'pongHTMLShort':"<img height=250px width=400px src=./src/media/pongGame.png><h3>Networked 6 Player Pong</h3>",
'puttonHTML':"<img height=250px width=400px src=./src/media/putton.png><h3>Putton</h3></div><p>This is a fun prototype of a webservice where users can create a button after making an account. Other users click these buttons to reveal secrets after X  amount of clicks. The clicks are shared between all users, and saved in MongoDB, the service is hosted through node.js and express.</p><a href=https://putton.herokuapp.com>Live Demo</a><a href=https://github.com/LegendaryBaddie/ButtonPalooza>Github</a>",
'puttonHTMLShort':"<img height=250px width=400px src=./src/media/putton.png><h3>Putton</h3></div>",
'audioHTML':"<img height=250px width=400px src=./src/media/audioViz.png><h3>Audio Visualizer</h3><p>I built a audio visualizer using the HTML Web Audio API. It animates the skeleton based off of the base kicks of the interpreted music. The art, and some of the code was provided by a partner.</p><a href=./audioviz/index.html>Live demo</a></div>",
'audioHTMLShort':"<img height=250px width=400px src=./src/media/audioViz.png><h3>Web App- Audio Visualizer</h3></div>",
'unnamedHTML':"<img height=250px width=400px src=./src/media/tugOWar.png><h3>Tug-o-War</h3><p>This fun webapp sets you head to head against another player. By mashing and bashing your arrow keys you can tug the bar to your side. Built in node.js, html and javascript.</p><a href=https://warrior-tug.herokuapp.com/>Live Demo</a><a href=https://github.com/LegendaryBaddie/SYNC2-TugOWar>Github</a></div>",
'unnamedHTMLShort':"<img height=250px width=400px src=./src/media/tugOWar.png><h3>Tug-o-War</h3></div>"
};
